### ISSUE TITLE
missing start of image marker

### ISSUE THREAD

**Issue by kaihendry** [tajtiattila/metadata#1]
https://s.natalian.org/2017-06-28/without.jpg is certainly a JPEG, so there must be bug in https://github.com/tajtiattila/metadata/blob/master/jpeg/jpeg.go#L69 ?

https://s.natalian.org/2017-06-28/gpsinfo.go

```
~/tmp/gps$ exiv2 pr -p a without.jpg | grep GPS
without.jpg: (No XMP data found in the file)
~/tmp/gps$ go run gpsinfo.go without.jpg
without.jpg
2017/06/28 11:34:02 Copy jpeg: missing start of image marker
panic: Copy jpeg: missing start of image marker


goroutine 1 [running]:
log.Panicln(0xc420037d80, 0x2, 0x2)
        /usr/lib/go/src/log/log.go:336 +0xc0
main.desc(0x7fff10237b5a, 0xb, 0x0, 0x0)
        /home/hendry/tmp/gps/gpsinfo.go:60 +0x355
main.main.func1(0x7fff10237b5a, 0xb, 0x559700, 0xc42006a1a0, 0x0, 0x0, 0x0, 0x0)
        /home/hendry/tmp/gps/gpsinfo.go:24 +0xcf
path/filepath.walk(0x7fff10237b5a, 0xb, 0x559700, 0xc42006a1a0, 0x4f52c8, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:351 +0x81
path/filepath.Walk(0x7fff10237b5a, 0xb, 0x4f52c8, 0x17, 0x558200)
        /usr/lib/go/src/path/filepath/path.go:398 +0x14c
main.main()
        /home/hendry/tmp/gps/gpsinfo.go:28 +0x8a
exit status 2
```

**Comment by tajtiattila** [comment]
Both exif.Decode and exif.Copy need a JPEG stream.

In your code exif.Decode reads (part of) the stream to decode the EXIF, leaving only the rest of the JPEG image to read for exif.Copy.

Seek to the beginning of the file between exif.Decode and exif.Copy.

**Comment by kaihendry** [comment]
Oops, thanks, `_, err = f.Seek(0, 0)` makes it all work. 

Planning to use your library at https://github.com/kaihendry/go-upload/tree/geo to write navigator.geolocation to JPEG uploads.
