### ISSUE TITLE
Photo: Next pointer is out of bounds; ignored

### ISSUE THREAD

**Issue by kaihendry** [tajtiattila/metadata#2]
When I try read https://s.natalian.org/2017-06-28/output.jpg with `exiv2` or https://www.pic2map.com/ I get an error.

exiv2 reports:
```
Error: Directory Photo: Next pointer is out of bounds; ignored.
Error: Directory (Last IFD item) with 672 entries considered invalid; not read.
```
`go run gpsinfo.go without.jpg` is what I ran.

* https://s.natalian.org/2017-06-28/gpsinfo.go
* https://s.natalian.org/2017-06-28/without.jpg

**Comment by tajtiattila** [comment]
I assumed that Sub-IFDs should be written without a next IFD pointer, since they serve no purpose. Having a zero next IFD pointer does no harm, so it should be written in any case.

I suspect exiv2 failed because of this problem, PTAL.
